# Default config.
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  TargetRubyVersion: 2.4
Metrics/AbcSize:
  Exclude:
    - test/**/*
Metrics/BlockLength:
  Exclude:
    - test/**/*
Metrics/MethodLength:
  Exclude:
    - test/**/*
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
